name: qsentry
channels: [conda-forge]
dependencies:
  - python=3.12
  - numpy=1.26.4
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - pyyaml
  - pip
  - pip:
      - "torch>=2.2,<2.9"
      - "pennylane==0.36.0"
      - "autoray==0.6.12"
